first java homework
vovaantonov/java pull request #1
Opened 2022-02-14 19:53 UTC by vovaantonov

2022-02-14 21:44 UTC, taraskarpenko requested changes
По условию задачи надо вывести значение `firstField` в виде
`---1234---` в методе returnInt
и в виде 
`~~~1234~~~` в методе main

Примените для этого форматирование строк

2022-02-14 22:55 UTC, vovaantonov commented
> По условию задачи надо вывести значение `firstField` в виде `---1234---` в методе returnInt и в виде `~~~1234~~~` в методе main
> 
> Примените для этого форматирование строк

Готово

2022-02-15 10:23 UTC, taraskarpenko commented
Вы использовали конкатенацию строк,
переделайте пожалуйста на форматирование строк
Для этого используется либо метод 
`String formattedString = String.format(format, values)`
либо
`System.out.printf(format, values);`

2022-02-15 10:57 UTC, vovaantonov commented
> Вы использовали конкатенацию строк, переделайте пожалуйста на форматирование строк Для этого используется либо метод `String formattedString = String.format(format, values)` либо `System.out.printf(format, values);`

Готово

2022-02-15 12:31 UTC, taraskarpenko approved these changes

2022-02-20 15:29 UTC, merged